Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// 5 – Pedir para o usuário informar o ano em que
//nasceu e o programa deve retornar a idade do usuário.
Var
anoNascimento, anoAtual, idade: inteiro

Inicio

anoAtual <- 2023
escreva("Digite o ano do seu nascimento: ")
leia(anoNascimento)
idade <- anoAtual - anoNascimento

escreva("Sua idade é: ", idade)

Fimalgoritmo